Repository DSC-Galgotias/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 added a Sorting Algorithm Visualizer
  Sorting Algorithm Visualizer/index.html
  Sorting Algorithm Visualizer/script.js
  Sorting Algorithm Visualizer/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#4 Ether SimpleStorage project
  Solidity_Simple_storage/.gitignore
  Solidity_Simple_storage/.prettierrc
  Solidity_Simple_storage/Readme.md
  Solidity_Simple_storage/SimpleStorage.sol
  Solidity_Simple_storage/SimpleStorage_sol_SimpleStorage.abi
  Solidity_Simple_storage/SimpleStorage_sol_SimpleStorage.bin
  Solidity_Simple_storage/deploy.js
  Solidity_Simple_storage/package.json
  Solidity_Simple_storage/yarn-error.log
  Solidity_Simple_storage/yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest2022

#6 Added a Ping Pong Game in Python.
  Ping Pong Game/pong1.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#10 React beginner static page added
  React-static-page/Readme.md
  React-static-page/Snippets/Dark_mode.png
  React-static-page/Snippets/light_mode.png
  React-static-page/package-lock.json
  React-static-page/package.json
  React-static-page/public/favicon.ico
  React-static-page/public/index.html
  React-static-page/public/logo192.png
  React-static-page/public/logo512.png
  React-static-page/public/manifest.json
  React-static-page/public/robots.txt
  React-static-page/src/App.js
  React-static-page/src/components/Header.js
  React-static-page/src/components/MainContent.js
  React-static-page/src/images/background-logo.png
  React-static-page/src/images/logo.png
  React-static-page/src/images/react-icon-dark.png
  React-static-page/src/index.html
  React-static-page/src/index.js
  React-static-page/src/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#11 qr code generator using react
  qr-code/README.md
  qr-code/package-lock.json
  qr-code/package.json
  qr-code/public/favicon.ico
  qr-code/public/index.html
  qr-code/public/logo192.png
  qr-code/public/logo512.png
  qr-code/public/manifest.json
  qr-code/public/robots.txt
  qr-code/src/App.js
  qr-code/src/QR.js
  qr-code/src/index.js
  qr-code/src/reportWebVitals.js
  qr-code/src/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#14 added word counter
  word counter/README.md
  word counter/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2022

#23 Updated Readme
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2022

#25 Added a digital clock
  digital-clock/app.js
  digital-clock/fonts/digital-7.ttf
  digital-clock/index.html
  digital-clock/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#26 Update README.md
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2022

#28 add weather app
  Weather App/index.html
  Weather App/script.js
  Weather App/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2022

#32 Word counter Web-application Using ReactJs
  WordCounter_Reactjs/.gitignore
  WordCounter_Reactjs/README.md
  WordCounter_Reactjs/package-lock.json
  WordCounter_Reactjs/package.json
  WordCounter_Reactjs/public/CNAME
  WordCounter_Reactjs/public/browserconfig.xml
  WordCounter_Reactjs/public/favicon-16x16.png
  WordCounter_Reactjs/public/favicon-32x32.png
  WordCounter_Reactjs/public/favicon-96x96.png
  WordCounter_Reactjs/public/index.html
  WordCounter_Reactjs/public/logo192.png
  WordCounter_Reactjs/public/logo512.png
  WordCounter_Reactjs/public/manifest.json
  WordCounter_Reactjs/public/robots.txt
  WordCounter_Reactjs/src/App.css
  WordCounter_Reactjs/src/App.js
  WordCounter_Reactjs/src/App.test.js
  WordCounter_Reactjs/src/Darkblue.jpg
  WordCounter_Reactjs/src/Wordcounter.js
  WordCounter_Reactjs/src/index.css
  WordCounter_Reactjs/src/index.js
  WordCounter_Reactjs/src/logo.svg
  WordCounter_Reactjs/src/reportWebVitals.js
  WordCounter_Reactjs/src/setupTests.js
  myntraclone/.vscode/settings.json
  myntraclone/downloads/Screenshot (115).png
  myntraclone/downloads/bag_icon.png
  myntraclone/downloads/clothimg1.png
  myntraclone/downloads/clothimg2.png
  myntraclone/downloads/clothimg3.png
  myntraclone/downloads/home_img.png
  myntraclone/downloads/myntra_logo.png
  myntraclone/downloads/profile_icon.png
  myntraclone/downloads/search_icon.png
  myntraclone/downloads/smallimg.png
  myntraclone/downloads/wishlist_icon.png
  myntraclone/index.html
  myntraclone/script.js
  myntraclone/style.css
  myntraclone/utils.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#33 Number Guessing Game in Python
  Number Guessing Game/Game.py
  Number Guessing Game/Score.txt
Labels: documentation, hacktoberfest-accepted, hacktoberfest2022

#42 added Edit notes fragment for the notes app (Kotlin)
  NotesFirebase(Kotlin)/app/src/main/java/com/example/notesfirebase/fragments/EditNotesFragment.kt
  NotesFirebase(Kotlin)/app/src/main/java/com/example/notesfirebase/fragments/ProfileFragment.kt
  NotesFirebase(Kotlin)/app/src/main/res/layout/fragment_profile.xml
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest2022

#47 Social Media Web-Application Using Reactjs
  Barbaric Web-application/.gitignore
  Barbaric Web-application/README.md
  Barbaric Web-application/package-lock.json
  Barbaric Web-application/package.json
  Barbaric Web-application/public/assets/ad.png
  Barbaric Web-application/public/assets/gift.png
  Barbaric Web-application/public/assets/heart.png
  Barbaric Web-application/public/assets/like.png
  Barbaric Web-application/public/assets/person/1.jpeg
  Barbaric Web-application/public/assets/person/10.jpeg
  Barbaric Web-application/public/assets/person/2.jpeg
  Barbaric Web-application/public/assets/person/3.jpeg
  Barbaric Web-application/public/assets/person/4.jpeg
  Barbaric Web-application/public/assets/person/5.jpeg
  Barbaric Web-application/public/assets/person/6.jpeg
  Barbaric Web-application/public/assets/person/7.jpeg
  Barbaric Web-application/public/assets/person/8.jpeg
  Barbaric Web-application/public/assets/person/9.jpeg
  Barbaric Web-application/public/assets/posts/1.jpeg
  Barbaric Web-application/public/assets/posts/10.jpeg
  Barbaric Web-application/public/assets/posts/2.jpeg
  Barbaric Web-application/public/assets/posts/3.jpeg
  Barbaric Web-application/public/assets/posts/4.jpeg
  Barbaric Web-application/public/assets/posts/5.jpeg
  Barbaric Web-application/public/assets/posts/6.jpeg
  Barbaric Web-application/public/assets/posts/7.jpeg
  Barbaric Web-application/public/assets/posts/8.jpeg
  Barbaric Web-application/public/assets/posts/9.jpeg
  Barbaric Web-application/public/index.html
  Barbaric Web-application/public/style.css
  Barbaric Web-application/src/App.css
  Barbaric Web-application/src/App.js
  Barbaric Web-application/src/DummyData.js
  Barbaric Web-application/src/components/Online/Online.css
  Barbaric Web-application/src/components/Online/Online.jsx
  Barbaric Web-application/src/components/Post/Post.jsx
  Barbaric Web-application/src/components/Post/post.css
  Barbaric Web-application/src/components/feed/Feed.jsx
  Barbaric Web-application/src/components/feed/feed.css
  Barbaric Web-application/src/components/rightbar/Rightbar.jsx
  Barbaric Web-application/src/components/rightbar/rightbar.css
  Barbaric Web-application/src/components/share/Share.jsx
  Barbaric Web-application/src/components/share/share.css
  Barbaric Web-application/src/components/sidebar/Sidebar.jsx
  Barbaric Web-application/src/components/sidebar/sidebar.css
  Barbaric Web-application/src/index.js
  Barbaric Web-application/src/pages/Home/Home.js
  Barbaric Web-application/src/pages/Home/home.css
  Barbaric Web-application/src/pages/topbar/Topbar.jsx
  Barbaric Web-application/src/pages/topbar/topbar.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2022

#48 News web-application
  NewsWeb/.gitignore
  NewsWeb/README.md
  NewsWeb/package-lock.json
  NewsWeb/package.json
  NewsWeb/public/favicon.ico
  NewsWeb/public/index.html
  NewsWeb/public/logo192.png
  NewsWeb/public/logo512.png
  NewsWeb/public/manifest.json
  NewsWeb/public/robots.txt
  NewsWeb/src/App.css
  NewsWeb/src/App.js
  NewsWeb/src/App.test.js
  NewsWeb/src/Mycomponent/Navbar.js
  NewsWeb/src/Mycomponent/News.js
  NewsWeb/src/Mycomponent/NewsItem.js
  NewsWeb/src/Mycomponent/SourceApi.js
  NewsWeb/src/index.css
  NewsWeb/src/index.js
  NewsWeb/src/reportWebVitals.js
  NewsWeb/src/setupTests.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2022

#53 added new project : Simon Game
  NotesFirebase(Kotlin)/.gradle/7.3.3/checksums/checksums.lock
  NotesFirebase(Kotlin)/.gradle/7.3.3/checksums/md5-checksums.bin
  NotesFirebase(Kotlin)/.gradle/7.3.3/checksums/sha1-checksums.bin
  Simon-Game/Simon-Game-main/.DS_Store
  Simon-Game/Simon-Game-main/README.md
  Simon-Game/Simon-Game-main/game.js
  Simon-Game/Simon-Game-main/how-to-play.html
  Simon-Game/Simon-Game-main/how.css
  Simon-Game/Simon-Game-main/images/simon.jpeg
  Simon-Game/Simon-Game-main/index.html
  Simon-Game/Simon-Game-main/sounds/blue.mp3
  Simon-Game/Simon-Game-main/sounds/green.mp3
  Simon-Game/Simon-Game-main/sounds/red.mp3
  Simon-Game/Simon-Game-main/sounds/wrong.mp3
  Simon-Game/Simon-Game-main/sounds/yellow.mp3
  Simon-Game/Simon-Game-main/styles.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#66 Age Calculater
  Age Calculator/app.js
  Age Calculator/index.html
  Age Calculator/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#68 Rock Paper Scissors using Python
  Rock_Paper_Scissors.py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#69 Black Jack Game
  Black_Jack game/README.md
  Black_Jack game/android-chrome-192x192.png
  Black_Jack game/android-chrome-512x512.png
  Black_Jack game/apple-touch-icon.png
  Black_Jack game/favicon-16x16.png
  Black_Jack game/favicon-32x32.png
  Black_Jack game/favicon.ico
  Black_Jack game/index.html
  Black_Jack game/index.js
  Black_Jack game/site.webmanifest
  Black_Jack game/style.css
  Counting_App/images/subway.jpg
  Counting_App/index.css
  Counting_App/index.html
  Counting_App/index.js
  Counting_App/subway.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#70 Link-Tree 🎄 Alternative with all customization.
  Link-Tree/README.md
  Link-Tree/index.html
  Link-Tree/screenshot.png
  Link-Tree/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#75 Port Scanner App
  Port-Scanner-main/.vscode/launch.json
  Port-Scanner-main/README.md
  Port-Scanner-main/port_scanner.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#77 Spotify Clone
  Spotify_clone/.vscode/settings.json
  Spotify_clone/Ishq_Tera.mp3
  Spotify_clone/downloads/1RW2.gif
  Spotify_clone/downloads/bcimg.jpg
  Spotify_clone/downloads/download.png
  Spotify_clone/downloads/music.gif
  Spotify_clone/index.html
  Spotify_clone/play-circle-regular.svg
  Spotify_clone/script.js
  Spotify_clone/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#73 Added a Play button in dice game
  Dice Game/dicee.html
  Dice Game/index.js
  Dice Game/styles.css
  word counter/index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#85 Simple Online Shopping Webpage
  Online Shopping Website/Project 1.pdf
  Online Shopping Website/css/responsive.css
  Online Shopping Website/css/style.css
  Online Shopping Website/css/utils.css
  Online Shopping Website/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#82 movie db
  Movie DB/.eslintrc.json
  Movie DB/.gitignore
  Movie DB/README.md
  Movie DB/components/Header.js
  Movie DB/components/HeaderItem.js
  Movie DB/components/Nav.js
  Movie DB/components/Results.js
  Movie DB/components/Thumbnail.js
  Movie DB/next.config.js
  Movie DB/package-lock.json
  Movie DB/package.json
  Movie DB/pages/_app.js
  Movie DB/pages/api/hello.js
  Movie DB/pages/index.js
  Movie DB/postcss.config.js
  Movie DB/public/favicon.ico
  Movie DB/public/vercel.svg
  Movie DB/styles/globals.css
  Movie DB/tailwind.config.js
  Movie DB/utils/requests.js
  Movie DB/yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest

#92 Python Program for Facial Recognition Login System
  Face_recognition_Python/login.py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#95 Basic calculator
  Basic_Calculator/Index.html
  Basic_Calculator/script.js
  Basic_Calculator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#93 Social Media website created on React has been added
  React Social-Media/package-lock.json
  React Social-Media/package.json
  React Social-Media/public/index.html
  React Social-Media/public/manifest.json
  React Social-Media/public/robots.txt
  React Social-Media/src/App.css
  React Social-Media/src/App.js
  React Social-Media/src/Components/AddPost.jsx
  React Social-Media/src/Components/Assets/feeds.json
  React Social-Media/src/Components/Assets/users.json
  React Social-Media/src/Components/Feed.jsx
  React Social-Media/src/Components/FeedNav.jsx
  React Social-Media/src/Components/Feeds.jsx
  React Social-Media/src/Components/FeedsCard.jsx
  React Social-Media/src/Components/LeftBar.jsx
  React Social-Media/src/Components/Login.jsx
  React Social-Media/src/Components/Main.jsx
  React Social-Media/src/Components/Nav.jsx
  React Social-Media/src/Components/RightBar.jsx
  React Social-Media/src/Components/Sign.jsx
  React Social-Media/src/Components/style.css
  React Social-Media/src/Theme.js
  React Social-Media/src/index.js
  React Social-Media/src/reportWebVitals.js
Labels: hacktoberfest-accepted, hacktoberfest

#96 Developed CryptoPaisa - A Web Application providing CryptoCurrency Details and News
  CryptoCurrency Web Application/.env.example
  CryptoCurrency Web Application/.eslintrc.js
  CryptoCurrency Web Application/.gitignore
  CryptoCurrency Web Application/README.md
  CryptoCurrency Web Application/package-lock.json
  CryptoCurrency Web Application/package.json
  CryptoCurrency Web Application/public/_redirects
  CryptoCurrency Web Application/public/cryptocurrency.png
  CryptoCurrency Web Application/public/index.html
  CryptoCurrency Web Application/src/App.css
  CryptoCurrency Web Application/src/App.js
  CryptoCurrency Web Application/src/app/store.js
  CryptoCurrency Web Application/src/components/CryptoDetails.jsx
  CryptoCurrency Web Application/src/components/Cryptocurrencies.jsx
  CryptoCurrency Web Application/src/components/Exchanges.jsx
  CryptoCurrency Web Application/src/components/Homepage.jsx
  CryptoCurrency Web Application/src/components/LineChart.jsx
  CryptoCurrency Web Application/src/components/Loader.jsx
  CryptoCurrency Web Application/src/components/Navbar.jsx
  CryptoCurrency Web Application/src/components/News.jsx
  CryptoCurrency Web Application/src/components/index.js
  CryptoCurrency Web Application/src/images/cryptocurrency.png
  CryptoCurrency Web Application/src/index.js
  CryptoCurrency Web Application/src/services/cryptoApi.js
  CryptoCurrency Web Application/src/services/cryptoNewsApi.js
Labels: hacktoberfest-accepted, hacktoberfest

#98 added an alarm clock
  Alarm Clock/assets/images__1_-removebg-preview.png
  Alarm Clock/assets/tone2.mp3
  Alarm Clock/index.html
  Alarm Clock/script.js
  Alarm Clock/style.css
Labels: hacktoberfest-accepted, help wanted, hacktoberfest

#105 Tetris Game Python
  Tetris Game Python/tetris.py
  Tetris Game Python/util.py
Labels: hacktoberfest-accepted, hacktoberfest

#111 Quiz app by Shashank
  Quiz App/index.html
  Quiz App/script.js
  Quiz App/style.css
  Resturant Website/package-lock.json
  Resturant Website/package.json
  Resturant Website/public/433087.png
  Resturant Website/public/index.html
  Resturant Website/public/manifest.json
  Resturant Website/public/robots.txt
  Resturant Website/src/Components/Data.json
  Resturant Website/src/Components/Footer.js
  Resturant Website/src/Components/Header.js
  Resturant Website/src/Components/Main.js
  Resturant Website/src/Components/Offer.js
  Resturant Website/src/Components/style.css
  Resturant Website/src/Components/test.json
  Resturant Website/src/Images/433087.png
  Resturant Website/src/index.css
  Resturant Website/src/index.js
  Resturant Website/src/reportWebVitals.js
  Resturant Website/src/setupTests.js
Labels: hacktoberfest-accepted, hacktoberfest

#112 Advance CSS Animation Effect
  Advance CSS Animation/index.html
  Advance CSS Animation/style.css
  CSSAnimation/index.html
  CSSAnimation/style.css
  Text Typing Animation/index.html
  Text Typing Animation/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#122 Adding Calculator Website.
  Calculator/BMI.css
  Calculator/BMI.html
  Calculator/BMI.js
  Calculator/image/BMI.jpg
  Calculator/image/BMI2.webp
  Calculator/image/BMI3.jpg
  Calculator/image/Screenshot.png
  Calculator/index.html
  Calculator/readme.md
  Calculator/script.js
  Calculator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#124 added picture-in-picture project
  picture-in-picture/favicon.png
  picture-in-picture/index.html
  picture-in-picture/script.js
  picture-in-picture/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#128 Added Online Banking app
  Bankist Project-Javascript/JS_Array-Methods.js
  Bankist Project-Javascript/JS_The-Map-Method.js
  Bankist Project-Javascript/JS_forEach-Method-in-Maps-Sets
  Bankist Project-Javascript/JS_forEach-Method.js
  Bankist Project-Javascript/JS_new-AT-Method.js
  Bankist Project-Javascript/icon.png
  Bankist Project-Javascript/index.css
  Bankist Project-Javascript/index.html
  Bankist Project-Javascript/logo.png
  Bankist Project-Javascript/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#126 beautiful form with full validation
  JS Form with validation/form.css
  JS Form with validation/form.js
  JS Form with validation/form_validation.html
Labels: hacktoberfest-accepted, hacktoberfest

#131 added my project folder quote-generator
  quote-generator/Thumbs.db
  quote-generator/favicon.png
  quote-generator/index.html
  quote-generator/script.js
  quote-generator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#134 Three Dimesional
  Three Dimensional Cube/index.html
  Three Dimensional Cube/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#130 Added Multiplication Game
  MultiplicationGame/README.md
  MultiplicationGame/index.html
  MultiplicationGame/javascript.js
  MultiplicationGame/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#136 added a drink water reminder using html-css-js
  Drink Water Reminder/index.html
  Drink Water Reminder/script.js
  Drink Water Reminder/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#138 added movie seat booking web-app
  Movie Seat Booking/index.html
  Movie Seat Booking/script.js
  Movie Seat Booking/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#140 Added a simple balloon popping game using html-css-js
  Balloon Popping Game/index.html
  Balloon Popping Game/script.js
  Balloon Popping Game/style.css
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#143 Added Food-online website code
  Food Deep/css/styles.css
  Food Deep/images/about.png
  Food Deep/images/food-lover.png
  Food Deep/images/food/beef.jpg
  Food Deep/images/food/jimmy.jpg
  Food Deep/images/food/soop.png
  Food Deep/images/icon.png
  Food Deep/images/shapes/background1.png
  Food Deep/images/shapes/background2.png
  Food Deep/images/shapes/bg1.png
  Food Deep/images/shapes/bg2.png
  Food Deep/images/shapes/bg3.png
  Food Deep/images/shapes/top.png
  Food Deep/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#141 Added the folder Omnifood
  Omnifood-project/.vscode/settings.json
  Omnifood-project/img/app-screen-1.png
  Omnifood-project/img/app-screen-2.png
  Omnifood-project/img/app-screen-3.png
  Omnifood-project/img/apple-touch-icon.png
  Omnifood-project/img/ben.jpg
  Omnifood-project/img/business-insider.png
  Omnifood-project/img/customer-1.jpg
  Omnifood-project/img/customer-2.jpg
  Omnifood-project/img/customer-3.jpg
  Omnifood-project/img/customer-4.jpg
  Omnifood-project/img/customer-5.jpg
  Omnifood-project/img/customer-6.jpg
  Omnifood-project/img/dave.jpg
  Omnifood-project/img/eating.jpg
  Omnifood-project/img/favicon-192.png
  Omnifood-project/img/favicon-512.png
  Omnifood-project/img/favicon.png
  Omnifood-project/img/forbes.png
  Omnifood-project/img/gallery-1.jpg
  Omnifood-project/img/gallery-10.jpg
  Omnifood-project/img/gallery-11.jpg
  Omnifood-project/img/gallery-12.jpg
  Omnifood-project/img/gallery-2.jpg
  Omnifood-project/img/gallery-3.jpg
  Omnifood-project/img/gallery-4.jpg
  Omnifood-project/img/gallery-5.jpg
  Omnifood-project/img/gallery-6.jpg
  Omnifood-project/img/gallery-7.jpg
  Omnifood-project/img/gallery-8.jpg
  Omnifood-project/img/gallery-9.jpg
  Omnifood-project/img/hannah.jpg
  Omnifood-project/img/hero-min.png
  Omnifood-project/img/hero.png
  Omnifood-project/img/hero.webp
  Omnifood-project/img/meal-1.jpg
  Omnifood-project/img/meal-2.jpg
  Omnifood-project/img/omnifood-logo.png
  Omnifood-project/img/steve.jpg
  Omnifood-project/img/techcrunch.png
  Omnifood-project/img/the-new-york-times.png
  Omnifood-project/img/usa-today.png
  Omnifood-project/manifest.webmanifest
  Omnifood-project/omnifood.css
  Omnifood-project/omnifood.html
  Omnifood-project/queries.css
  Omnifood-project/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#142 added product specific landing page
  Sneakers_shop/.gitattributes
  Sneakers_shop/README.md
  Sneakers_shop/app.js
  Sneakers_shop/images/NMD.png
  Sneakers_shop/images/aj1.png
  Sneakers_shop/images/aj2.png
  Sneakers_shop/images/back.png
  Sneakers_shop/images/contact.png
  Sneakers_shop/images/gift.png
  Sneakers_shop/images/magnifying-glass-solid.svg
  Sneakers_shop/images/new.png
  Sneakers_shop/images/nmd2.png
  Sneakers_shop/images/return-box.png
  Sneakers_shop/images/superstar.png
  Sneakers_shop/images/superstar2.png
  Sneakers_shop/images/truck.png
  Sneakers_shop/images/yeezy.png
  Sneakers_shop/images/yeezy2.png
  Sneakers_shop/index.html
  Sneakers_shop/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#149 Hacktoberfest2
  EMI Calculator/EMI_Calculator.html
Labels: hacktoberfest-accepted, hacktoberfest

#150 Hacktoberfest3
  Analog Clock/clock.png
  Analog Clock/index.html
  Analog Clock/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#153 Added a app folder related to age in minutes calculator
  Age_in_Minutes  Calculator/.gitignore
  Age_in_Minutes  Calculator/.idea/.gitignore
  Age_in_Minutes  Calculator/.idea/.name
  Age_in_Minutes  Calculator/.idea/compiler.xml
  Age_in_Minutes  Calculator/.idea/gradle.xml
  Age_in_Minutes  Calculator/.idea/misc.xml
  Age_in_Minutes  Calculator/app/.gitignore
  Age_in_Minutes  Calculator/app/build.gradle
  Age_in_Minutes  Calculator/app/proguard-rules.pro
  Age_in_Minutes  Calculator/app/src/androidTest/java/com/example/agetominutes/ExampleInstrumentedTest.kt
  Age_in_Minutes  Calculator/app/src/main/AndroidManifest.xml
  Age_in_Minutes  Calculator/app/src/main/java/com/example/agetominutes/MainActivity.kt
  Age_in_Minutes  Calculator/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Age_in_Minutes  Calculator/app/src/main/res/drawable/ic_launcher_background.xml
  Age_in_Minutes  Calculator/app/src/main/res/layout-land/activity_main.xml
  Age_in_Minutes  Calculator/app/src/main/res/layout/activity_main.xml
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Age_in_Minutes  Calculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Age_in_Minutes  Calculator/app/src/main/res/values-night/themes.xml
  Age_in_Minutes  Calculator/app/src/main/res/values/colors.xml
  Age_in_Minutes  Calculator/app/src/main/res/values/strings.xml
  Age_in_Minutes  Calculator/app/src/main/res/values/themes.xml
  Age_in_Minutes  Calculator/app/src/main/res/xml/backup_rules.xml
  Age_in_Minutes  Calculator/app/src/main/res/xml/data_extraction_rules.xml
  Age_in_Minutes  Calculator/app/src/test/java/com/example/agetominutes/ExampleUnitTest.kt
  Age_in_Minutes  Calculator/build.gradle
  Age_in_Minutes  Calculator/gradle.properties
  Age_in_Minutes  Calculator/gradle/wrapper/gradle-wrapper.jar
  Age_in_Minutes  Calculator/gradle/wrapper/gradle-wrapper.properties
  Age_in_Minutes  Calculator/gradlew
  Age_in_Minutes  Calculator/gradlew.bat
  Age_in_Minutes  Calculator/settings.gradle
Labels: hacktoberfest-accepted, hacktoberfest

#151 add new annoying button
  Annoying Button/index.css
  Annoying Button/index.html
  Annoying Button/index.js
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#148 Draw Happy Diwali in Python Turtle in Python
  Draw Happy Diwali/Happy_Diwali.py
  Draw Happy Diwali/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#154 Hacktoberfest4
  Egg Catcher/basket.png
  Egg Catcher/bullseye1.png
  Egg Catcher/collision_detection.js
  Egg Catcher/functions.js
  Egg Catcher/hen-right.png
  Egg Catcher/index.html
  Egg Catcher/jquery.min.js
  Egg Catcher/script.js
  Egg Catcher/style.css
  Egg Catcher/variables.js
Labels: hacktoberfest-accepted, hacktoberfest

#157 added an insect catching game
  Insect Catching Game/index.html
  Insect Catching Game/script.js
  Insect Catching Game/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#158 job application form template
  job application form/index.html
  job application form/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#160 whack-a-mole game using html,css and js
  Whack-a-Mole/dirt.png
  Whack-a-Mole/index.html
  Whack-a-Mole/mole.jpg
  Whack-a-Mole/mole.png
  Whack-a-Mole/script.js
  Whack-a-Mole/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#163 Added Diabetes Predictor USing Python
  Diabetes_Predictor/DIABETES.ipynb
  Diabetes_Predictor/README.MD
  Diabetes_Predictor/diabetes.csv
Labels: hacktoberfest-accepted, hacktoberfest

#165 Update style.css
  Online Shopping Website/css/style.css
Labels: enhancement, hacktoberfest-accepted

#161 Added a Coin Flipper Project
  Coin Flipper/index.html
Labels: hacktoberfest

#166 Added NEWS App
  NEWS/.gitignore
  NEWS/.idea/.gitignore
  NEWS/.idea/compiler.xml
  NEWS/.idea/deploymentTargetDropDown.xml
  NEWS/.idea/gradle.xml
  NEWS/.idea/jarRepositories.xml
  NEWS/.idea/markdown-navigator-enh.xml
  NEWS/.idea/markdown-navigator.xml
  NEWS/.idea/misc.xml
  NEWS/.idea/vcs.xml
  NEWS/app/.gitignore
  NEWS/app/build.gradle
  NEWS/app/google-services.json
  NEWS/app/proguard-rules.pro
  NEWS/app/src/androidTest/java/com/sandeepgupta/NEWS/ExampleInstrumentedTest.java
  NEWS/app/src/main/AndroidManifest.xml
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/EntertainmentFragment.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/FixedTabPagerAdapter.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/MainActivity.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/News.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/NewsAdapter.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/NewsFragment.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/ScienceFragment.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/SportsFragment.java
  NEWS/app/src/main/java/com/sandeepgupta/NEWS/TechnologyFragment.java
  NEWS/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  NEWS/app/src/main/res/drawable/ic_launcher_background.xml
  NEWS/app/src/main/res/drawable/ic_outline_volume_up_24.xml
  NEWS/app/src/main/res/layout/activity_main.xml
  NEWS/app/src/main/res/layout/home_fragment.xml
  NEWS/app/src/main/res/layout/list_items.xml
  NEWS/app/src/main/res/layout/news_fragment.xml
  NEWS/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  NEWS/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  NEWS/app/src/main/res/mipmap-hdpi/ic_launcher.png
  NEWS/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  NEWS/app/src/main/res/mipmap-mdpi/ic_launcher.png
  NEWS/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  NEWS/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  NEWS/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  NEWS/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  NEWS/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  NEWS/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  NEWS/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  NEWS/app/src/main/res/mipmap-xxxhdpi/newslogo.png
  NEWS/app/src/main/res/values-night/strings.xml
  NEWS/app/src/main/res/values-night/themes.xml
  NEWS/app/src/main/res/values/colors.xml
  NEWS/app/src/main/res/values/strings.xml
  NEWS/app/src/main/res/values/themes.xml
  NEWS/app/src/test/java/com/sandeepgupta/NEWS/ExampleUnitTest.java
  NEWS/build.gradle
  NEWS/gradle.properties
  NEWS/gradle/wrapper/gradle-wrapper.jar
  NEWS/gradle/wrapper/gradle-wrapper.properties
  NEWS/gradlew
  NEWS/gradlew.bat
  NEWS/settings.gradle
Labels: hacktoberfest

#164 Adding my version of 2048 game in JS
  2048/game.js
  2048/index.html
Labels: documentation, hacktoberfest

#174 Added game Menja
  menjaa/index.html
  menjaa/script.js
  menjaa/style.css
  tower-blocks/LICENSE.txt
  tower-blocks/index.html
  tower-blocks/script.js
  tower-blocks/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#179 app calcule a budget
  budget/.sass-cache/48fc4009cfa51173e407a5ee20581ee10de4a690/style.scssc
  budget/index.html
  budget/main.js
  budget/style.css
  budget/style.css.map
  budget/style.scss
Labels: documentation, hacktoberfest

#182 Created a game in python for testing typing speed and accuracy
  Typing Speed Game/background.jpg
  Typing Speed Game/icon.png
  Typing Speed Game/sentences.txt
  Typing Speed Game/speed typing.py
  Typing Speed Game/type-speed-open.png
Labels: hacktoberfest-accepted, hacktoberfest

#184 Created Netflix Data Analysis
  Netflix Data Analysis/Netflix Data Analysis.ipynb
  Netflix Data Analysis/netflix_titles.csv
Labels: hacktoberfest-accepted, hacktoberfest

#187 created a amazon-prime-login-page-clone
  Amazon-Prime-Login-Page-Clone/index.css
  Amazon-Prime-Login-Page-Clone/index.html
  Amazon-Prime-Login-Page-Clone/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#189 Form Response to Email
  Form to Email/README.md
  Form to Email/home.html
  Form to Email/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#190 Guess Game App Using React Native
  guessGameApp/App.js
  guessGameApp/app.json
  guessGameApp/assets/adaptive-icon.png
  guessGameApp/assets/favicon.png
  guessGameApp/assets/fonts/OpenSans-Bold.ttf
  guessGameApp/assets/fonts/OpenSans-Regular.ttf
  guessGameApp/assets/icon.png
  guessGameApp/assets/images/background.png
  guessGameApp/assets/images/success.png
  guessGameApp/assets/splash.png
  guessGameApp/babel.config.js
  guessGameApp/components/game/GuessLogItem.js
  guessGameApp/components/game/NumberContainer.js
  guessGameApp/components/ui/Card.js
  guessGameApp/components/ui/InstructionText.js
  guessGameApp/components/ui/PrimaryButton.js
  guessGameApp/components/ui/Tittle.js
  guessGameApp/constants/colors.js
  guessGameApp/package-lock.json
  guessGameApp/package.json
  guessGameApp/screens/GameOverScreen.js
  guessGameApp/screens/GameScreen.js
  guessGameApp/screens/StartGameScreen.js
Labels: hacktoberfest-accepted, hacktoberfest

#191 Created encryption and decryption using python
  Encrypt decrypt/main.py
  Encrypt decrypt/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#195 new entries
  Maurer/README.md
  Maurer/maurer.py
  Pascal-Tic-Tac-Toe/Readme.md
  Pascal-Tic-Tac-Toe/tictactoe.pas
  Pascal-Tic-Tac-Toe/tictactoe_freepascal.pas
Labels: hacktoberfest-accepted, hacktoberfest

#198 Added a emoji rating app
  Emoji rating app/index.html
  Emoji rating app/index.js
  Emoji rating app/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#199 Added a Mouse-Event game
  Mouse-Event/index.html
  Mouse-Event/index.js
  Mouse-Event/style.css
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#202 Added a step progress bar
  Step-progress-bar/README.md
  Step-progress-bar/index.html
  Step-progress-bar/index.js
  Step-progress-bar/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#203 Added a bomber man game for issue #201
  Bomber Man game/README.md
  Bomber Man game/index.html
  Bomber Man game/script.js
  Bomber Man game/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#205 Added Drum Kit project
  Drum Kit/.gitignore
  Drum Kit/Procfile
  Drum Kit/app.js
  Drum Kit/package-lock.json
  Drum Kit/package.json
  Drum Kit/public/images/crash.png
  Drum Kit/public/images/kick.png
  Drum Kit/public/images/snare.png
  Drum Kit/public/images/tom1.png
  Drum Kit/public/images/tom2.png
  Drum Kit/public/images/tom3.png
  Drum Kit/public/images/tom4.png
  Drum Kit/public/index.js
  Drum Kit/public/sounds/crash.mp3
  Drum Kit/public/sounds/kick-bass.mp3
  Drum Kit/public/sounds/snare.mp3
  Drum Kit/public/sounds/tom-1.mp3
  Drum Kit/public/sounds/tom-2.mp3
  Drum Kit/public/sounds/tom-3.mp3
  Drum Kit/public/sounds/tom-4.mp3
  Drum Kit/public/styles.css
  Drum Kit/views/index.ejs
Labels: hacktoberfest-accepted, hacktoberfest

#206 drag-drop using html,css,js added
  dragdrop/dragdrop.css
  dragdrop/dragdrop.html
  dragdrop/dragdrop.js
  dragdrop/pic.jpg
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#207 Android app that convert km to miles
  covertit/.gitignore
  covertit/.idea/.gitignore
  covertit/.idea/compiler.xml
  covertit/.idea/gradle.xml
  covertit/.idea/misc.xml
  covertit/app/.gitignore
  covertit/app/build.gradle
  covertit/app/proguard-rules.pro
  covertit/app/src/androidTest/java/com/example/covertit/ExampleInstrumentedTest.java
  covertit/app/src/main/AndroidManifest.xml
  covertit/app/src/main/java/com/example/covertit/MainActivity.java
  covertit/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  covertit/app/src/main/res/drawable/ic_launcher_background.xml
  covertit/app/src/main/res/drawable/miles.png
  covertit/app/src/main/res/layout/activity_main.xml
  covertit/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  covertit/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  covertit/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  covertit/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  covertit/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  covertit/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  covertit/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  covertit/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  covertit/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  covertit/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  covertit/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  covertit/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  covertit/app/src/main/res/values-night/themes.xml
  covertit/app/src/main/res/values/colors.xml
  covertit/app/src/main/res/values/strings.xml
  covertit/app/src/main/res/values/themes.xml
  covertit/app/src/test/java/com/example/covertit/ExampleUnitTest.java
  covertit/build.gradle
  covertit/gradle.properties
  covertit/gradle/wrapper/gradle-wrapper.jar
  covertit/gradle/wrapper/gradle-wrapper.properties
  covertit/gradlew
  covertit/gradlew.bat
  covertit/settings.gradle
Labels: hacktoberfest-accepted, hacktoberfest

#208 basic web browser code
  webBrowser/Driver.java
  webBrowser/GUIManager.java
  webBrowser/actionListener.java
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#209 netflix page
  netflix front page/README.md
  netflix front page/css/style.css
  netflix front page/img/background.jpg
  netflix front page/img/logo.png
  netflix front page/img/tab-content-1.png
  netflix front page/img/tab-content-2-1.png
  netflix front page/img/tab-content-2-2.png
  netflix front page/img/tab-content-2-3.png
  netflix front page/index.html
  netflix front page/js/main.js
Labels: hacktoberfest-accepted, hacktoberfest

#223 The Organizer
  The Organizer/THE_ORGANIZER.py
Labels: hacktoberfest-accepted, hacktoberfest

#222 Web page
  portfolio/Home.html
  portfolio/about.html
  portfolio/bg.jpg
  portfolio/contacts.html
  portfolio/index.html
  portfolio/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#225 Create DiceGui.py
  DiceGui/DiceGui.py
Labels: hacktoberfest-accepted, hacktoberfest

#228 Create tictactoe.py
  py_tictactoe/tictactoe.py
Labels: hacktoberfest-accepted, hacktoberfest

#226 Create hangman_game.py
  hangman_game/hangman_game.py
Labels: hacktoberfest-accepted, hacktoberfest
